---
- name: "Ensure google-cloud-sdk.repo"
  template:
    src: templates/google-cloud-sdk.repo.j2
    dest: /etc/yum.repos.d/google-cloud-sdk.repo
    owner: root
    group: root
    mode: 0644

- name: Ensure google-cloud-sdk
  dnf:
    name: 
      - google-cloud-sdk
      - google-cloud-sdk-app-engine-python
      - google-cloud-sdk-app-engine-python-extras
      - google-cloud-sdk-app-engine-java
      - google-cloud-sdk-app-engine-go
      - google-cloud-sdk-bigtable-emulator
      - google-cloud-sdk-cbt
      - google-cloud-sdk-cloud-build-local
      - google-cloud-sdk-pubsub-emulator
      - google-cloud-sdk-app-engine-grpc
      - google-cloud-sdk-datalab
      - google-cloud-sdk-datastore-emulator
      - google-cloud-sdk-firestore-emulator
      - google-cloud-sdk-tests
        #- kubectl


    state: "{{ package_state }}"

