---
- name: "Ensure google-cloud-sdk.repo"
  template:
    src: templates/google-chrome.repo.j2
    dest: /etc/yum.repos.d/google-chrome.repo
    owner: root
    group: root
    mode: 0644

- name: Ensure google-cloud-sdk
  dnf:
    name: 
      - google-chrome-stable

    state: "{{ package_state }}"

