---
# this should be replaced with
# https://github.com/markosamuli/ansible-pyenv
- name: Ensure pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv'
    dest: /home/{{ user }}/.pyenv
    version: v1.2.15
  become: true
  become_user: "{{ user }}"
