---
- name: Ensure rpmfusion
  dnf:
    name: 
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm 
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm 
    state: "{{ package_state }}"

