---
- name: Debug message from projects.yml
  debug:
    msg: System message from the projects.yml

- name: "Ensure /home/{{ user }}/Projects"
  file:
    path: "/home/{{ user }}/Projects"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  become: false

- name: "Ensure /home/{{ user }}/Projects/local"
  file:
    path: "/home/{{ user }}/Projects/local"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  become: false

# Set up k8's contrib
- name: "kubernetes folder"
  file:
    path: "/home/{{ user }}/Projects/kubernetes"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  become: false

- name: kube contrib
  git:
    repo: https://github.com/kubernetes/contrib.git
    dest: "/home/{{ user }}/Projects/kubernetes/contrib"
    version: master

- name: kube contrib
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: "/home/{{ user }}/Projects/kubernetes/kubespray"
    version: v2.11.0
  become: false

# Set up spinnaker
- name: "spinnaker project directory"
  file:
    path: "/home/{{ user }}/Projects/spinnaker"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  become: false

- name: spinnaker
  git:
    repo: https://github.com/spinnaker/spinnaker.git
    dest: "/home/{{ user }}/Projects/spinnaker/spinnaker"
    version: version-0.28.0
  become: false
