---
- name: Debug message from users.yml
  debug:
    msg: System message from the users.yml

- name: "bashrc for {{ user }}"
  template:
    src: templates/bashrc.j2
    dest: ~{{ user }}/.bashrc
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
