---
- name: os specific facts
  include_vars: "{{item }}"
  with_first_found:
    - "{{ ansible_os_family }}".yml
  tags: vars

	
- dnf:
    #name: vim-enhanced
    #state: "{{ role_state['package'] }}"
    name: install atom
    name: 'https://atom.io/download/rpm'
    state: present
    
