---
# tasks file for atom
- name: run OS specific tasks
  included_tasks: "{{task_item }}"
  with_first_found:
    - "{{ ansible_distribution }}"
    - "{{ ansible_os_family.yml }}"
  tags: tasks
  loop_control:
    loop_var: task_item

