---
# Make links fo runit file
# Created symlink /etc/systemd/system/multi-user.target.wants/jenkins.service → /etc/systemd/system/jenkins.service.
#
- name: "link jenkins unit file"
  file:
    src: "{{ unit_files_dir }}/{{ jenkins_service_name }}"
    dest: "/etc/systemd/system/multi-user.target.wants/{{ jenkins_service_name }}"
    owner: root
    group: root
    state: link
  become: true

- name: "start {{ jenkins_service_name }}"
  systemd:
    name: "{{ jenkins_service_name }}"
    state: started
    enabled: true
  become: true

